### ISSUE TITLE
Can't find the 0.1.1 release in Maven Central

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/kotlin-coworker#42]
Hello! 
I can't find the 0.1.1 release in Maven Central. Right now it is [about 19 hours](https://github.com/camunda-community-hub/kotlin-coworker/actions/runs/4182749128) since the release was completed but it cannot be retrieved and [found](https://mvnrepository.com/search?q=org.camunda.community.extension.kotlin.coworker%3Acoworker-spring-boot-starter) in Maven Central.

@camunda-community-hub/devrel Can you help me, please? 🙂

**Comment by berndruecker** [comment]
Hi @aivinog1 - this required a manual release on the Sonatype server from us - I just did that now.
If you want to avoid waiting for manual releases you can use the auto-release property in your Github action: https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD#performing-a-release. This will require the latest parent pom 1.4.1 to be used. we introduced this one or two weeks back.

Hope that helps!
Bernd
